---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: Run role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        semaphoreui_dialect: sqlite
        semaphoreui_cookie_hash: "test"
        semaphoreui_cookie_encryption: "test"
        semaphoreui_access_key_encryption: "Q+Sg52Iq4+cjGz0dBaGwzE9s6vUMeISt/pxQ9iszkGw="
